service: serverless-sns-example

provider:
  name: aws
  runtime: nodejs6.10

functions:
  message:
    handler: handler.message
    events:
      - sns: sns-example-topic

plugins:
  - serverless-offline
  - serverless-offline-sns

custom:
  serverless-offline-sns:
    port: 4002
    debug: true 